In [1]:
from extract_from_pdf import *
docs = query_pdfs_for_tables()
res = adapt_tables_to_common_schema(docs)
df = tables_as_data_frame(res)
print(df)

[nltk_data] Downloading package punkt to /Users/apdoshi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
This function will be deprecated in a future release and `unstructured` will simply use the DEFAULT_MODEL from `unstructured_inference.model.base` to set default model name
Some weights of the model checkpoint at microsoft/table-transformer-structure-recognition were not used when initializing TableTransformerForObjectDetection: ['model.backbone.conv_encoder.model.layer2.0.downsample.1.num_batches_tracked', 'model.backbone.conv_encoder.model.layer3.0.downsample.1.num_batches_tracked', 'model.backbone.conv_encoder.model.layer4.0.downsample.1.num_batches_tracked']
- This IS expected if you are initializing TableTransformerForObjectDetection from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TableTransformerForObjectDetection from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

<class 'list'>
                             Department/Bond Category   Revenue  Expenses  \
0                                      Property Taxes    69,232         0
1                                         Sales Taxes    21,960         0
2                                         Other Taxes    19,124         0
3                         Licenses, Permits, and Fees    14,284         0
4                               Fines and Forfeitures       264         0
5                           Use of Money and Property    28,876     1,821
6                                   Intergovernmental     8,903         0
7                                Charges for Services    23,645        55
8                    Developer Fees and Contributions       600         0
9                                               Other     4,456        40
10                                     Total Revenues   191,344     2,386
11                               Current Expenditures   192,118         0
12                                     Capital Outlay     2,386         0
13                                       Debt Service         0         0
14                                 Total Expenditures   194,504         0
15      Excess (Deficiency) of Revenues Over (Unde...     (774)  (12,816)
16                     Other Financing Sources (Uses)  (12,775)     1,021
17                             Change in Fund Balance  (13,549)  (31,464)

   Net Income
0      69,232
1      21,960
2      19,124
3      14,284
4         264
5      27,055
6       8,903
7      23,590
8         600
9       4,416
10    188,958
11    192,118
12      2,386
13          0
14    194,504
15     11,042
16   (11,754)
17     17,915

In [2]:
df

,Department/Bond Category,Revenue,Expenses,Net Income
0,Property Taxes,"69,232",0,"69,232"
1,Sales Taxes,"21,960",0,"21,960"
2,Other Taxes,"19,124",0,"19,124"
3,"Licenses, Permits, and Fees","14,284",0,"14,284"
4,Fines and Forfeitures,264,0,264
5,Use of Money and Property,"28,876","1,821","27,055"
6,Intergovernmental,"8,903",0,"8,903"
7,Charges for Services,"23,645",55,"23,590"
8,Developer Fees and Contributions,600,0,600
9,Other,"4,456",40,"4,416"
10,Total Revenues,"191,344","2,386","188,958"
11,Current Expenditures,"192,118",0,"192,118"
12,Capital Outlay,"2,386",0,"2,386"
13,Debt Service,0,0,0
14,Total Expenditures,"194,504",0,"194,504"
15,Excess (Deficiency) of Revenues Over (Unde...,(774),"(12,816)","11,042"
16,Other Financing Sources (Uses),"(12,775)","1,021","(11,754)"
17,Change in Fund Balance,"(13,549)","(31,464)","17,915"